application: be-taptaphero-301214
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /users
  script: Controller.users.app
- url: /tapgame/.*
  script: Controller.tapgame.app  
#Endpoints handler
- url: /_ah/api/.*
  script: Endpoints.user_api.app
  
- url: /.*
  script: Controller.main.app

libraries:
- name:  webapp2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0