application: be-taptaphero-301214
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: .*
  script: /controller/main.app
- url: /tapgame/.*
  script: /controller/tapgame.app
- url: /users/.*
  script: /controller/users.app
libraries:
- name:  webapp2
  version: "2.5.1"